@MM.Web_HostAddress = http://localhost:5046

GET http://localhost:5046/books/
Accept: application/json

###
GET http://localhost:5046/books/A89F6CD7-4693-457B-9009-02205DBBFE45
Accept: application/json

###
POST http://localhost:5046/books
Accept: application/json
Content-Type: application/json

{
    "Id": "A89F6CD7-4693-457B-9009-02205DBBFE44",
    "Title": "Hoobit",
    "Author": "J.R.R. Tolkien",
    "Price": 8.99
}

###
DELETE http://localhost:5046/books/A89F6CD7-4693-457B-9009-02205DBBFE44
Accept: application/json

###
POST http://localhost:5046/books/A89F6CD7-4693-457B-9009-02205DBBFE44/pricehistory
Accept: application/json
Content-Type: application/json

{
    "Id": "A89F6CD7-4693-457B-9009-02205DBBFE44",
    "Price": 18.99
}

###
POST https://localhost:7136/users
Accept: application/json
Content-Type: application/json

{
  "Email": "test@test.com",
  "Password": "Pass@word1"
}

###
POST https://localhost:7136/users/login
Accept: application/json
Content-Type: application/json

{
  "Email": "test@test.com",
  "Password": "Pass@word1"
}


###
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3NzAzNzAzNjQsIkVtYWlsQWRkcmVzcyI6InRlc3RAdGVzdC5jb20iLCJleHAiOjE3NzAzNzM5NjQsIm5iZiI6MTc3MDM3MDM2NH0.GvkiYufNBCos9EI7rr20rtCDtFGk57BDfKw_qD19ZHU

POST https://localhost:7136/cart
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "BookId": "A89F6CD7-4693-457B-9009-02205DBBFE45",
  "Quantity": 1
}

###
GET https://localhost:7136/cart
Accept: application/json
Authorization: Bearer {{token}}

###
